resource_types:
- name: gerrit
  type: docker-image
  source:
    repository: us.gcr.io/concourse-resources/gerrit-resource

resources:
- name: example-gerrit
  type: gerrit
  source:
    url: https://review.example.com
    query: status:open project:example
    cookies: ((gerrit-cookies))

jobs:
- name: example-ci
  plan:
  # Trigger this job for every new patch set
  - get: example-gerrit
    version: every
    trigger: true

  - task: example-ci
    file: example-gerrit/ci.yml